### ISSUE TITLE
Annoying new behavior to cycle through different sizes in 1.6.4

### ISSUE THREAD

**Issue by he-sk** [fikovnik/ShiftIt#259] opened 2017-12-14 19:38 UTC
When I press Ctrl-Alt-Cmd-Right to put a window to the right half of the screen, the window size cycles through different width. If find this behavior very irritating and have downgraded to version 1.6.3 because of this.

Is there an option to deactivate this behavior? Alternatively, a default width for the start of the cycle would be useful.

**Comment by fikovnik** [comment] 2017-12-15 10:39
There is a fix on the way https://github.com/fikovnik/ShiftIt/pull/258 sorry for the inconvenience.

**Comment by fikovnik** [comment] 2017-12-15 12:00
Duplicate of https://github.com/fikovnik/ShiftIt/issues/254

**Closed by fikovnik** 2017-12-15 12:00 UTC
Labels: duplicate
