### ISSUE TITLE
Remove dependency on X11

### ISSUE THREAD

**Issue by apennebaker** [fikovnik/ShiftIt#120] opened 2013-10-25 17:00 UTC
If we can remove the dependency on X11, and use only Cocoa libs, this would make it easier for more Mac users to install ShiftIt.

**Comment by SuperHenkie** [comment] 2015-04-21 23:01
Any chance you could add the non-X11 version to [Homebrew Cask](http://caskroom.io/)? (there is already a [cask](https://github.com/caskroom/homebrew-cask/blob/00ce74ef6833c2baeb707d57958759911b3660a1/Casks/shiftit.rb) for the X11-dependant version) 
 
After running `brew cask install shiftit` and messing around with installing xquartz (also through home cask, btw) I finally got it to work, but it would have been easier if it works straight out of the box :)

**Comment by fikovnik** [comment] 2015-04-22 07:42
OK, I need to spend some time on this since it apparently does not work. The idea is to have the X11 support loaded at runtime only when X11 is installed. In other words you might only need X11 for compilation.

Which version of ShiftIt have you used?

**Comment by fikovnik** [comment] 2015-04-22 07:47
Btw: the X11 ShiftIt cask is outdated - there is now 1.6.1 release

**Comment by SuperHenkie** [comment] 2015-04-22 09:01
I've got ShiftIt version 1.6, but if I check for updates (from within ShiftIt) it says "ShiftIt 1.6 is currently the newest version available."

FYI - I have OS X 10.10.1 (Yosemite) and never did anything with X11 whatsoever (I don't even know what it is).

It would be great if you can keep the cask up to date, by the way. Perhaps it's better to make a cask for 'latest version' (pointing to a correct URL which always contains the latest version) rather than having to update it for every version manually?

**Comment by fikovnik** [comment] 2015-04-22 11:56
The problem (that I caused) is that the old version sync with development tree instead of the master one. Can you try again - I hope I changed that.

If not, you can either download it directly form the releases or wait for this change to be applied in cask:
https://github.com/caskroom/homebrew-cask/pull/10783

**Comment by SuperHenkie** [comment] 2015-04-22 12:46
OK, thanks, I'll await the cask merge and update it from there (I prefer to keep my software installed through homebrew / cask as much as possible, for easier maintenance).

**Comment by fikovnik** [comment] 2015-04-27 12:32
It has been merged in [#10783](https://github.com/caskroom/homebrew-cask/pull/10783)

**Comment by cipriancaba** [comment] 2015-04-27 12:52
Just updated to 1.6.1 via automatic updates from the NO X11 version and now I am prompted to install X11.. Please remove this dependency

**Closed** 2015-04-27 17:24 UTC

**Comment by fikovnik** [comment] 2015-04-27 17:47
I hope I finally debugged the issue and made a fix followed by a new release 1.6.2. Hope it will work.

**Comment by SuperHenkie** [comment] 2015-05-01 13:36
Great, I tested it (got 1.6.3 actually) and it all seemed to work fine now. Can't be 100% sure because last time, I installed the X11 replacement thing (X11 isn't on yosemite anymore, but instead it came up with Quartz libraries or something, not sure) so that is still on there now. 

But I didn't get any errors. Also like to see the new high-res icon in the menu bar :)

I'll soon be able to test it again on another mac (which does not have x11 / quartz / whatever installed) and I will let you know if I still encounter any problems there!

**Comment by cipriancaba** [comment] 2015-05-01 16:22
I can confirm 1.6.3 works on a brand new Yosemite install.. Thanks

**Comment by SuperHenkie** [comment] 2015-05-01 16:36
:thumbsup: I will recommend ShiftIt to everybody :)

**Comment by AugustusZ** [comment] 2015-11-25 21:12
Finally!
