### ISSUE TITLE
ShiftIt commands not working at all with MacOS Sierra update

### ISSUE THREAD

**Issue by Pivotal-Jayson-Hairston** [fikovnik/ShiftIt#216] opened 2016-09-30 16:48 UTC
ShiftIt commands not working at all with MacOS Sierra update

**Comment by fikovnik** [comment] 2016-09-30 20:13
I have not upgraded yet, could you please be more specific?

**Comment by Neejoh** [comment] 2016-10-01 08:10
I'm running macOS and ShiftIt doesn't run at all in my case.
I've tried using 1.6.3, freshly downloaded. It first says it's not signed, then when I "open anyway" via Security & Privacy it doesn't do much. In the Activity Monitor it says the process is running, but only with 4KB memory and nothing else to show for and no way to interact with it. 
Tried killing it, both via the Activity Monitor and by killing the PID via terminal, no such luck. 

Nothing mentioned in /var/logs

Let me know what you need to get to the bottom of this :]

**Comment by fikovnik** [comment] 2016-10-02 17:00
Did you re-enable the shiftit in the "Accessibilty" -> "Allow the apps  below to control your computer"?

**Comment by Neejoh** [comment] 2016-10-03 19:37
Can't find anything Shiftit related in Accessibility.

**Comment by fikovnik** [comment] 2016-10-03 20:43
It is not even in the menu bar?

**Comment by Neejoh** [comment] 2016-10-04 05:49
Nope.

**Comment by unRob** [comment] 2016-10-05 16:52
On multiple monitors, having a single full-screen app anywhere makes that app's frontmost window the target of all ShiftIt commands, even if that app is not active or focused. Otherwise, ShiftIt works just as before the Sierra upgrade.

The debug log outputs:

```
2016-10-05 12:51:30.747 ShiftIt[842/0x7fffce7a73c0] [lvl=3] -[ShiftItAppDelegate invokeShiftItActionByIdentifier_:] Execution of ShiftIt action: right failed: Windows in fullscreen are not supported
NSError stack trace:
org.shiftitapp.shifit.error:20103 - Windows in fullscreen are not supported
```

**Comment by fikovnik** [comment] 2016-10-05 17:07
So it does work (well apart of this) on Sierra.

**Comment by unRob** [comment] 2016-10-05 17:48
Yes, as long as there is no visible full-screen window it works for me on 10.12 with ShiftIt version 1.6.3

**Comment by sunnykgupta** [comment] 2016-10-06 12:25
Perfect. I was facing the same issue. I had a full-screen window on a second monitor. So I'm guessing it was hogging up the shift commands.
Now it is working for me too in macOS Sierra.

**Comment by deldrid1** [comment] 2016-10-06 13:40
Any ideas what the bug might be with having a full-screen window open on a second monitor?  I lean heavily on shift-it for monitor 1, but my second monitor is always a full-screen instance of Fusion...

**Comment by Pivotal-Jayson-Hairston** [comment] 2016-10-06 15:05
I just now seen these responses. It is now working for me as well now. It
just started working after about two days. I'm not sure if a full screen
was in another window, but I was using a second monitor when I first
upgraded and tried to use ShiftIt. I will lookout for the bug, but I think
its working fine now.

I do believe it is possible that I had to re-enable the "Allow the apps
below to control your computer". I did this before reading your
recommendation because I needed to for a newer app I was installing.
Perhaps that has fixed it now.

Thanks ShiftIt Team!

Jayson Hairston
GSS - PCF
Senior Customer Engineer
Pivotal Global Support Services (GSS)
Email: jhairston@pivotal.io
Direct Tel: +1 (415) 777-4868
Office Hours: Mon-Fri 9am to 5pm EST
Pivotal GSS Contact & Escalations:
https://discuss.zendesk.com/hc/en-us/articles/203809556

**Comment by HybridProgrammer** [comment] 2016-10-10 12:55
I can confirm the same behavior that was described by @unRob. I have multiple monitors and had one application in full screen mode. I used the two finger swipe (magic mouse, 4 fingers with touchpad) to switch back to the main desktop window and ShiftIt started working again. 

I did not have to re-enable ShiftIt in Accessibility. Those settings carried over after the update to macOS Sierra.

**Comment by coolsebz** [comment] 2016-10-16 00:36
Recently hit the same problem. Even though the settings were kept after upgrading I tried re-enabling ShiftIt in Accessibility but to no success

**Comment by Neejoh** [comment] 2016-10-16 11:40
I haven't updated anything and it suddenly works?!
I have a single monitor but Spotify in full screen, and it still works. Again, I didn't change anything. I think macOS updated though... Now running macOS 10.12.1 beta (16B2548a)

**Comment by rain0r** [comment] 2016-10-16 20:43
Unfortunately, I have the same problem since the upgrade to Sierra.

This is what I tried:

- Uninstall and re-install shiftit
- Disable and re-enable the Accessibility permission
- reboot (lol)

When I execute `/Applications/ShiftIt.app/Contents/MacOS/ShiftIt` from command line it always tells me to grant the Accessibility permissions.

When I start shiftit from spotlight nothing happens.

**Comment by fikovnik** [comment] 2016-10-17 13:37
I will try to upgrade during the week to give it a try.

**Comment by synthetiv** [comment] 2016-10-18 12:42
Just want to confirm that I too found ShiftIt to be unreliable after upgrading to Sierra – sometimes the keyboard commands would work, sometimes they wouldn't. Thanks to others in this thread, I now realize that when it works, it's because I don't have any full-screen apps currently active (they can be _running,_ they just can't be _active_). Any time it's not working, all I have to do is switch out of any full-screen apps (usually Terminal), and then I can use the hotkeys.

I can't say I've had any of the other problems folks are reporting – ShiftIt stayed in my menu bar after I upgraded without my having to do anything special.

**Comment by fikovnik** [comment] 2016-10-19 18:53
Thanks for all the comments. I upgraded to sierra today. I committed a change that hopefully fixes this issue. I was wondering if any of you could check it? It is in the latest develop branch 14ca76a1f66197e4df140f989525b659d449eca9. Thanks!

**Comment by unRob** [comment] 2016-10-24 16:08
I can confirm it is working in the edge cases it wasn't responding before. Great work @fikovnik , thanks!

**Comment by rain0r** [comment] 2016-10-25 21:01
Does anybody else experience the issue that ShiftIt is not even starting up? Not even the new beta.

First time starting ShiftIt brings up the dialog that says I should enable it in Settings -> Accessibilty.
After doing so and clicking on "recheck" the window disappears and nothing happens.
Starting ShiftIt again results in ... nothing.

**Comment by philosopherdog** [comment] 2016-10-25 22:16
@fikovnik The beta seems to have fixed the issue so far. thanx.

**Comment by fikovnik** [comment] 2016-10-31 15:34
@rain0r - have you tried the beta - 1.6.4?

**Comment by minhoolee** [comment] 2016-11-02 02:58
Is the beta supposed to be listed as version 1.6.3 in the app? I unzipped the zip file at the 1.6.4 beta release, but I am still encountering the same problem (full screen on second monitor) with the unzipped app. This is on Mac OS Sierra and I have modified the Accessibility preferences (it works normally).

**Comment by rain0r** [comment] 2016-11-05 22:11
@fikovnik  - yes and I experience the same issues.

**Comment by petekowalsky** [comment] 2016-11-22 01:21
@fikovnik ShiftIt is an every day tool for me too, and with my triple-monitor setup after Sierra upgrade, I have the same issues, and have the same current experience as @minhoolee above with the 1.6.4 beta build. Unfortunately, it's not working for me, but if I move any full-screen windows off and use a regular workspace on any monitor it works fine (same as with 1.6.3 release).

Hope you can fix it soon @fikovnik - this is a GREAT tool!

**Comment by fikovnik** [comment] 2016-11-22 04:12
This is difficult for me to reproduce, but I will try to add more debugging output to narrow it down. Thanks for the patience!

**Comment by davidsandoz** [comment] 2017-03-03 07:48
Is there any plan to release a stable 1.6.4?

**Comment by atomictangerine** [comment] 2017-11-28 22:59
Was having issues with it too but your pre-release 1.6.4 works great. Thank you!! I love this tool btw. So helpful.

**Comment by fikovnik** [comment] 2017-11-29 08:45
Thank you. I think @rca was working on it in #248

**Comment by rca** [comment] 2017-11-29 13:15
@fikovnik I opened up that PR to shore up some of the issues I was having when attempting to release this. Some aspects don’t work for me, and I certainly don’t have the auth to push out the official release. 

I’m happy to work on this, but need your help.  Are you available on irc or gitter to discuss real time one of these days?  I’m guessing resolving the issues I’m hitting won’t take more than an hour to resolve. My local time is UTC-5

**Closed** 2018-03-01 13:58 UTC

**Comment by holmesmi** [comment] 2018-08-16 13:59
I'm on 1.6.6, and I'm still seeing this issue. Is it just me? Should I open a new issue, or reopen this one?
